apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          resources:
            limits:
              memory: "250Mi"
              cpu: "0.5"
          envFrom:
            - configMapRef:
                name: rabbitmq-env
          ports:
            - containerPort: 15672
