apiVersion: apps/v1
kind: Deployment
metadata:
  name: hadoop
spec:
  selector:
    matchLabels:
      app: hadoop
  template:
    metadata:
      labels:
        app: hadoop
        name: name-node
    spec:
      containers:
        - name: namenode
          image: apache/hadoop:3
          command:
            ["mkdir", "/tmp/hadoop-hadoop/dfs/name", "&&", "hdfs", "namenode"]
          resources:
            limits:
              memory: "500Mi"
              cpu: "0.5"
          ports:
            - containerPort: 9870
          volumeMounts:
            - name: hadoop-config
              mountPath: /opt/hadoop/etc/hadoop
          env:
            - name: ENSURE_NAMENODE_DIR
              value: "/tmp/hadoop-root/dfs/name"
        # other configurations...
      volumes:
        - name: hadoop-config
          configMap:
            name: hadoop-env
