apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crm-web
spec:
  rules:
    - host: crm.coinhalo.world
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: crm-web
                port:
                  number: 80
