apiVersion: apps/v1
kind: Deployment
metadata:
  name: mattermost
spec:
  selector:
    matchLabels:
      app: mattermost
  template:
    metadata:
      labels:
        app: mattermost
        name: mattermost
    spec:
      containers:
        - name: mattermost
          image: mattermost/mattermost-enterprise-edition:release-9.3
          ports:
            - containerPort: 8065
          envFrom:
            - configMapRef:
                name: mattermost-config

---
apiVersion: v1
kind: Service
metadata:
  name: mattermost
spec:
  type: NodePort
  selector:
    app: mattermost
    name: mattermost
  ports:
    - port: 8065
      targetPort: 8065
      nodePort: 30030
