# Kubernetes API version
apiVersion: apps/v1
# Deployment object
kind: Deployment
metadata:
  name: postgresdb
  labels:
    external: "true"
spec:
  selector:
    # labels the pods
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        # The label the pods created from the pod template should have
        app: postgresdb
    spec:
      containers:
        # The container name to execute pods
        - name: postgresdb
          # pull postgresimage from docker hub
          image: kong:3.4.1
          ports:
            # Assign ports to expose container
            - containerPort: 8000
            - containerPort: 8443
            - containerPort: 8001
            - containerPort: 8444
          envFrom:
            # Load the environment variables/PostgresSQL credentials
            - configMapRef:
                # This should be the ConfigMap name created ealier
                name: kong-env
          resources:
            limits:
              cpu: 1
              memory: 1Gi
