# Kubernetes API version
apiVersion: apps/v1
# Deployment object
kind: Deployment
metadata:
  name: kong-gateway
spec:
  selector:
    # labels the pods
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        # The label the pods created from the pod template should have
        app: kong
        name: kong-gateway
    spec:
      containers:
        # The container name to execute pods
        - name: kong
          # pull postgresimage from docker hub
          image: 11112003/kong-rebuild:latest
          ports:
            # Assign ports to expose container
            - containerPort: 8000
            - containerPort: 8001
            - containerPort: 8002
            - containerPort: 8443
            - containerPort: 8444
            - containerPort: 8445
          envFrom:
            # Load the environment variables/PostgresSQL credentials
            - configMapRef:
                # This should be the ConfigMap name created ealier
                name: kong-env
