# Kubernetes API version
apiVersion: apps/v1
# Deployment object
kind: Deployment
metadata:
  name: kong-db
spec:
  selector:
    # labels the pods
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        # The label the pods created from the pod template should have
        app: kong
        name: kong-db
    spec:
      containers:
        # The container name to execute pods
        - name: kong-db
          # pull postgresimage from docker hub
          image: postgres:16
          ports:
            # Assign ports to expose container
            - containerPort: 5432
          envFrom:
            # Load the environment variables/PostgresSQL credentials
            - configMapRef:
                # This should be the ConfigMap name created ealier
                name: kong-env
          volumeMounts:
            # The volume mounts  for the container
            - mountPath: /var/lib/postgres/data
              name: db-data
      # Volumes attached to the pod
      volumes:
        - name: db-data
          persistentVolumeClaim:
            # reference the PersistentVolumeClaim
            claimName: kong-pvc
