apiVersion: v1
# Kind for service
kind: Service
metadata:
  # Name your service
  name: kong
  labels:
    app: kong
spec:
  # Choose how to expose your service
  ports:
    # The port number to expose the service
    - protocol: TCP
      port: 5432
      targetPort: 5432
  # Pod to route service traffic
  selector:
    app: kong
