apiVersion: v1
# Kind for service
kind: Service
metadata:
  # Name your service
  name: kong
  labels:
    app: kong
spec:
  type: NodePort
  ports:
    # The port number to expose the service
    - protocol: TCP
      port: 5432
      targetPort: 5432
      name: database-port
    - protocol: TCP
      port: 8445
      targetPort: 8445
      nodePort: 30009
      name: kong-admin
    - protocol: TCP
      port: 8443
      targetPort: 8443
      nodePort: 30010
      name: kong-api
    - protocol: TCP
      port: 8444
      targetPort: 8444
      nodePort: 30011
      name: kong-admin-api
  # Pod to route service traffic
  selector:
    app: kong