apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redis-ingress
spec:
  rules:
    - host: "redis.footing.world"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: redis
                port:
                  number: 6379
          - path: /manager
            pathType: ImplementationSpecific
            backend:
              service:
                name: redis
                port:
                  number: 8001
