apiVersion: v1
# Kind for service
kind: Service
metadata:
  # Name your service
  name: redis
  labels:
    app: redis
spec:
  # Choose how to expose your service
  type: NodePort
  externalName: redis.footing.world
  selector:
    app: redis
